#include "EndGameMenu.h"

#include "Core/Renderer/ConsoleColours.h"
// Q - Quit
CHAR_INFO endExitSprite[] =
{
	{' ', BACKGROUND_PINK}, {' ', BACKGROUND_PINK}, {' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK}, {' ', BACKGROUND_PINK}, {' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},
	{' ', BACKGROUND_PINK}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_PINK}, {' ', BACKGROUND_BLACK} ,{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK}, {' ', BACKGROUND_BLACK} ,{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_PINK}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_PINK}, {' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK}, {' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},
};
//Background
CHAR_INFO endBackground[24576];


//Game Over!
CHAR_INFO EndGameOverSprite[] =
{
	{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},
	{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},
	{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK}, {' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},
};
//Victory!
CHAR_INFO EndVictorySprite[] =
{
	{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},
	{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},
	{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},
	{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_PINK},{' ', BACKGROUND_PINK},
};
//CONSTRUCTOR 
EndMenuIcon::EndMenuIcon()
	: m_bInitialised(false)
{
}

// DESTRUCTOR
EndMenuIcon::~EndMenuIcon()
{
}

void EndMenuIcon::SetPosition(Vector2 position)
{
	m_position.x = position.x;
	m_position.y = position.y;
}

Vector2 EndMenuIcon::GetPosition()
{
	return m_position;
}

void EndMenuIcon::Initialise()
{//sprite is the same size as the screen. If statements are used to create a pattern and a frame
	for (int i = 0; i < 24576; i++) {
		if (i % 3 == 0 ) endBackground[i] = { 0, BACKGROUND_WHITE };
		else endBackground[i] = { 0, BACKGROUND_SKYBLUE };
		if (i < 512 || i > 24063 || i % 256 < 4 || (i + 4) % 256 < 4)endBackground[i] = { 0, BACKGROUND_BLUE };
			
	}
	switch (GetSpriteID()) {
	case 0:Sprite::Initialise(EndGameOverSprite, Vector2(32,11)); Sprite::SetPosition(SCREEN_WIDTH / 2 - 15, 25); break;
	case 1:Sprite::Initialise(EndVictorySprite, Vector2(48, 5)); Sprite::SetPosition(SCREEN_WIDTH / 2 - 24, 25);  break;
	case 2:Sprite::Initialise(endBackground, Vector2(SCREEN_WIDTH, SCREEN_HEIGHT));Sprite::SetPosition(0, 0); break;
	case 3:Sprite::Initialise(endExitSprite, Vector2(27, 5)); Sprite::SetPosition(SCREEN_WIDTH / 2 - 13, 80); break;
	}

	m_bInitialised = true;
}
void EndMenuIcon::Render(ASCIIRenderer* pRenderer)
{
	if (!m_bInitialised)
		return;
	Sprite::Render(pRenderer);
}
void EndMenuIcon::Update()
{
	if (!m_bInitialised || !m_Active)
		return;
}






