#include "EnemyShip.h"
#include "Core/Renderer/ConsoleColours.h"
#include "Core/Maths/Vector2.h"
#include "Core/Renderer/AnimatedSprite.h"

//#include <Windows.h>

const int ENEMY_SPRITE_WIDTH = 30;
const int ENEMY_SPRITE_HEIGHT = 5;

CHAR_INFO EnemyShipSprite0[ENEMY_SPRITE_ANIMATION_FRAMES][ENEMY_SPRITE_WIDTH * ENEMY_SPRITE_HEIGHT] =
{
	{
		{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },
		{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },
		{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK }, { ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK }, { ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK }
	},
	{
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK }, { ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK }, { ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK }, { ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK }, { ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK }, { ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK }
	},
	{
	{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },
		{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_DARK_GREY },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK }, { ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK }, { ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK }
	},
	{
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_GREY }, { ' ' ,BACKGROUND_GREY }, { ' ' ,BACKGROUND_GREY }, { ' ' ,BACKGROUND_GREY }, { ' ' ,BACKGROUND_GREY }, { ' ' ,BACKGROUND_GREY }, { ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK }, { ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK }, { ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_GREY },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK }, { ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK }, { ' ' ,BACKGROUND_GREY }, { ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
	},

};

const int MOVEMENT_AMOUNT = 4;
//constructor
EnemyShip::EnemyShip()
	:m_bInitialised(false)
	, m_AnimationTimer(0.0f)
	, m_Active(true)

{
}
//destructor
EnemyShip::~EnemyShip()
{
}

void EnemyShip::Initialise(Vector2& position, int fireRate, int sprite,  float initialTime)
{
	
	m_AnimationTimer = initialTime;
	int SCREEN_HEIGHT = 96;

	AnimatedSprite::Initialise(&EnemyShipSprite0[0][0], Vector3(ENEMY_SPRITE_WIDTH, ENEMY_SPRITE_HEIGHT, ENEMY_SPRITE_ANIMATION_FRAMES));
	Vector2 startPosition(position.x - (AnimatedSprite::GetSize().x / 2), position.y - (AnimatedSprite::GetSize().y / 2));
	SetPosition(startPosition);

	m_bInitialised = true;

}

bool EnemyShip::Update(float deltaTime)
{
	if (!m_bInitialised || !m_Active)
		return false;
	m_AnimationTimer += deltaTime;
	if (m_AnimationTimer >= 1.0f)
	{
		if (GetAnimationFrame() == 2)
		{
			
			m_AnimationTimer -= 0.15f;
			SetAnimationFrame(3);
			
		}
		else if (GetAnimationFrame() == 3)
		{
			m_Active = false;
			
		}
		else
		{
			m_AnimationTimer -= 1.0f;
			SetAnimationFrame(GetAnimationFrame() == 0 ? 1 : 0);
		}

		
	}

	return false;
}

void EnemyShip::Render(ASCIIRenderer* pRenderer)
{
	if (!m_bInitialised || !m_Active)
		return;

	AnimatedSprite::Render(pRenderer);
}

//removes enemy ship
void EnemyShip::Die()
{
	if (GetAnimationFrame() < 2)
	{
		m_AnimationTimer = 0.85f;
		SetAnimationFrame(2);
	}

}



//decreases position on x axis causing it to move left towards playership
void EnemyShip::Approach(float deltaTime)
{
	SetPosition(Vector2(GetPosition().x - 2, GetPosition().y));
	Update(deltaTime);
}
