#include "PlayerShip.h"
#include "../ASCII_GAME/Core/Maths/Vector2.h"
#include "../ASCII_GAME/Core/Renderer/ConsoleColours.h"
#include <Windows.h>
//speed
const int MOVEMENT_SPEED = 2;
//sprite design
CHAR_INFO ShipSprite[] =
{
	{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },
	{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_BLACK },
	{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_BRIGHT_RED },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_SKYBLUE },
	{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_BRIGHT_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_SKYBLUE },
	{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_BRIGHT_RED },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_SKYBLUE },
	{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_BRIGHT_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_SKYBLUE },
	{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_BRIGHT_RED },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_SKYBLUE },
	{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_BRIGHT_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_SKYBLUE },
	{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_WHITE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_SKYBLUE },{ 0, BACKGROUND_BLACK },
	{ 0, BACKGROUND_RED },{ 0, BACKGROUND_RED },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK },{ 0, BACKGROUND_BLACK }
};

PlayerShip::PlayerShip()
	:m_UpKey(0)
	, m_DownKey(0)
	, m_bInitialised(false)
{
}

PlayerShip::~PlayerShip()
{
}

//player movement
void PlayerShip::Initialise(Vector2& position, int upKey, int downKey)
{
	m_UpKey = upKey;
	m_DownKey = downKey;

	Sprite::Initialise(ShipSprite, Vector2(18, 10));

	Vector2 startPosition(3, 48);
	SetPosition(startPosition);

	m_bInitialised = true;
}
//update sprite
void PlayerShip::Update()
{
	if (!m_bInitialised)
		return;

	if (UpKeyPressed())
	{
		MoveUp();
	}
	if (DownKeyPressed())
	{
		MoveDown();
	}

}
//render sprite on screen
void PlayerShip::Render(ASCIIRenderer* pRenderer)
{
	if (!m_bInitialised)
		return;

	Sprite::Render(pRenderer);
}
//movement
void PlayerShip::MoveUp()
{
	SetPosition(Vector2(GetPosition().x, GetPosition().y - MOVEMENT_SPEED));

	if (GetPosition().y < 14)
	{
		MoveDown();
	}
}

void PlayerShip::MoveDown()
{
	SetPosition(Vector2(GetPosition().x, GetPosition().y + MOVEMENT_SPEED));

	if (GetPosition().y + GetSize().y > SCREEN_HEIGHT)
	{
		MoveUp();
	}
}

bool PlayerShip::UpKeyPressed()
{
	return (GetKeyState(m_UpKey) < 0);
}

bool PlayerShip::DownKeyPressed()
{
	return (GetKeyState(m_DownKey) < 0);
}
